package io.metersphere.commons.model;

import java.io.Serializable;

public class WorkspaceDTO implements Serializable {
    private String id;

    private String organizationId;

    private String name;

    private String description;

    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table workspace
     *
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace.id
     *
     * @return the value of workspace.id
     *
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace.id
     *
     * @param id the value for workspace.id
     *
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace.organization_id
     *
     * @return the value of workspace.organization_id
     *
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace.organization_id
     *
     * @param organizationId the value for workspace.organization_id
     *
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace.name
     *
     * @return the value of workspace.name
     *
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace.name
     *
     * @param name the value for workspace.name
     *
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace.description
     *
     * @return the value of workspace.description
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace.description
     *
     * @param description the value for workspace.description
     *
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace.create_time
     *
     * @return the value of workspace.create_time
     *
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace.create_time
     *
     * @param createTime the value for workspace.create_time
     *
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
